title: Trae Zhang's Homepage
page-top-title: Trae Zhang
top-section-bg-text: Computer Science
home-subtitle: Trae Zhang&infp;|&intp;张启睿
copyright-text: '&copy; Trae Zhang 2023-2025. All Rights Reserved.'
